apiVersion: v1
kind: Namespace
metadata:
  name: ai-demo # Change this value if you want a different namespace name
  labels:
    name: minio-dev # Change this value to match metadata.name
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: ai-demo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzF1WlhOamFHVnlPbWRvY0Y5a1ZreDFTM1ZtVFhSNFlVZzBUVkZRYm5Kc2JVYzRTM1pVVGs5MlZYZzBUMVowV200PSIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXMXBibVZ6WTJobGNtTnNiM1ZrT2pFME9UZEFVMmx1WVE9PSIKCQl9Cgl9Cn0=