apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: ai-demo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzF1WlhOamFHVnlPbWRvY0Y5bVIwVXdWR0ptTkU1R1NYaG5OVUpJVnpCUFpWbFRSRk54UzNCMFpVbzBOR0ZDY3prPSIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXMXBibVZ6WTJobGNtTnNiM1ZrT2pFME9UZEFVMmx1WVE9PSIKCQl9Cgl9Cn0=