apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: ai-demo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXMXBibVZ6WTJobGNtTnNiM1ZrT2pFME9UZEFVMmx1WVE9PSIKCQl9LAoiZ2hjci5pbyI6IHsKICAgICAgICAgICAgImF1dGgiOiAiWVcxdVpYTmphR1Z5T21kb2NGOUVlR3BxT0hGWVIycHdkbWR5WVdveFNXRnRVelpFUlZkU1JHeHVkMkl4VFhwclYyWT0iCiAgICAgICAgfQoJfQp9Cg==