# Deploys a new Namespace for the MinIO Pod
apiVersion: v1
kind: Namespace
metadata:
  name: ai-demo # Change this value if you want a different namespace name
  labels:
    name: minio-dev # Change this value to match metadata.name
---
apiVersion: v1
data:
  MINIO_ACCESS_KEY: RXNjaGVyY2xvdWRfQ1ZfZGVtbw==
  MINIO_SECRET_KEY: dXJGMkZiVVd2ODVkWXRqQg==
  GIT_USER: amnescher
  GIT_TOKEN: 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
kind: Secret
metadata:
  name: minio-secret
  namespace: ai-demo
type: Opaque